baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Printed Camera'

[[menus.main]]
name = 'Cameras'
pageRef = '/cameras'
weight = 20

[[menus.main]]
name = 'Backs'
pageRef = '/backs'
weight = 20

[[menus.main]]
name = 'Bodies'
pageRef = '/bodies'
weight = 20

[[menus.main]]
name = 'Lenses'
pageRef = '/lenses'
weight = 20

[[menus.main]]
name = 'Shutters'
pageRef = '/Shutters'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
